$(document).ready(function(){$('.dropdown__item').on('mouseenter',function(){$(this).addClass('dropdown__item-is-active').find('.dropdown__sub').stop().fadeIn(300)}).on('mouseleave',function(){$(this).removeClass('dropdown__item-is-active').find('.dropdown__sub').stop().fadeOut(300)});$(document).on('click',".dropdown__icon",function(e){return!1});$('.dropdown__item').each(function(){if($(this).find('.dropdown__sub').length){$(this).find('a').first().append("<span class='dropdown__icon'></span>")}})
$('.mobile-mainmenu-btn').sidr({name:'sidr-mobile-mainmenu',source:'#panel-mainmenu'});$(document).on('click',".sidr-class-form-link",function(e){$.sidr('close','sidr-mobile-mainmenu')});$('.mobile-filtr-btn').sidr({name:'sidr-mobile-filtr',source:'#panel-filtr',renaming:!1});chosenParams={no_results_text:"Ничего не найдено",disable_search_threshold:10,width:"100%"}
$('select').chosen(chosenParams);$('input').iCheck({checkboxClass:'icheckbox_minimal-blue',radioClass:'iradio_minimal-blue'});var from=$(".range_from").val();var to=$(".range_to").val();var min=0;if($(".range_to").attr("data-start-value"))
{var max=$(".range_to").attr("data-start-value")}else{var max=0}
if(!from)from=0;if(!to)to=100000;$(".range").ionRangeSlider({hide_min_max:!0,keyboard:!0,min:min,max:max,from:from,to:to,type:'double',step:50,onChange:function(data){$(".range_from").val(data.from);$(".range_to").val(data.to)},onUpdate:function(data){$(".range_from").val(data.from);$(".range_to").val(data.to)}});var range0=$(".range").eq(0).data("ionRangeSlider");var range1=$(".range").eq(1).data("ionRangeSlider");$(document).on('dblclick',".irs-from, .irs-to, .irs-single",function(e){if(range0){range0.reset()}
if(range1){range1.reset()}});$(document).on('click',".filtr input[type='reset']",function(e){setTimeout(function(){$('input').iCheck('update');if(range0){range0.reset()}
if(range1){range1.reset()}
$('select').trigger('chosen:updated')},500)});$(window).on("resize",function(event){if($(window).width()>768){$.sidr('close','sidr-mobile-mainmenu');$.sidr('close','sidr-mobile-filtr')}});$('.form-link, .sidr-class-form-link, .question').magnificPopup({type:'inline',preloader:!1,focus:'#name',removalDelay:300,mainClass:'my-mfp-zoom-in',tClose:'Закрыть (Esc)',callbacks:{beforeOpen:function(){if($(window).width()<768){this.st.focus=!1}else{this.st.focus='#name'}}}});$(document).on('click',".btn-view",function(e){$('.btn-view').removeClass("active");$(this).addClass("active");$('.items').removeClass('view-list').removeClass('view-list-img').removeClass('view-tile').addClass($(this).attr('data-view'))});$('.sidr').swipe({excludedElements:'button, input, select, textarea, .noSwipe',swipeLeft:function(event,direction,distance,duration,fingerCount){$.sidr('close','sidr-mobile-mainmenu');$.sidr('close','sidr-mobile-filtr')},});$(document).on('click',".compare-panel-side-open",function(e){if($(".compare-panel").hasClass("active")){$(".compare-panel").animate({right:0},500,function(){$(".compare-panel-content").hide()}).removeClass("active")}else{$(".compare-panel-content").show();$(".compare-panel").animate({right:'250px'},500,function(){$(".compare-panel").removeAttr("style")}).addClass("active")}
return!1});$(document).on('click',".compare-panel-mobile-open",function(e){if($(".compare-panel").hasClass("active")){$(".compare-panel-content").slideUp(500,function(){$(".compare-panel").removeClass("active");$(".compare-panel").removeAttr("style");$(".compare-panel-content").removeAttr("style")})}else{$(".compare-panel-content").slideDown(500,function(){$(".compare-panel").addClass("active")})}
return!1});$(".big-banners-corousel").owlCarousel({dots:!0,nav:!1,loop:!0,autoplay:!0,autoplayTimeout:10000,smartSpeed:1000,items:1});$(".spec-products-corousel").each(function(index){var corousel_items=$(this).children('div').length;var corousel_loop=y=corousel_items>4?!0:!1;$(this).owlCarousel({autoplay:!0,autoplayTimeout:6000,autoplayHoverPause:!0,loop:corousel_loop,nav:!0,items:4,responsive:{0:{items:1},540:{items:2},768:{items:3},960:{items:4},}})});$(".partners-corousel").owlCarousel({autoplay:!1,loop:!0,nav:!0,items:3,responsive:{0:{items:1},540:{items:2},768:{items:3},960:{items:6},1280:{items:6},}});$(".news-corousel").owlCarousel({autoplay:!1,loop:!1,nav:!0,items:2,responsive:{0:{items:1},768:{items:2},}})});function recoverPass(login){$.post('/auth/recover/',{'login':login},function(data){if(data.success){$('.recoverMyText').fadeIn(500);$('.recoverMyText').delay(2500).fadeOut(500)}else{$('.recoverMyTextError').fadeIn(500);$('.recoverMyTextError').delay(2500).fadeOut(500)}},'json');return!1}