var App={win:$(window),doc:$(document),is_mobile:detectmob(),ms_ie:/(MSIE|Trident\/|Edge\/)/i.test(navigator.userAgent),max_mobile_width:992,wheeling:!1,};function detectmob(){if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i))
{return!0}
else{return!1}}
function debounce(func,wait,immediate){var timeout;return function(){var context=this,args=arguments;var later=function(){timeout=null;if(!immediate)func.apply(context,args)};var callNow=immediate&&!timeout;clearTimeout(timeout);timeout=setTimeout(later,wait);if(callNow)func.apply(context,args)}};function fileBoxesInit(inputs){Array.prototype.forEach.call(inputs,function(input)
{var label=input.parentNode,labelVal=label.innerHTML;input.addEventListener('change',function(e)
{var fileName='';if(this.files&&this.files.length>1)
fileName=(this.getAttribute('data-multiple-caption')||'').replace('{count}',this.files.length);else fileName=e.target.value.split('\\').pop();if(fileName)
label.querySelector('span').innerHTML=fileName;else label.innerHTML=labelVal});input.addEventListener('focus',function(){input.classList.add('has-focus')});input.addEventListener('blur',function(){input.classList.remove('has-focus')})})};function check_scroll(){if($(window).scrollTop()==0){$('body').addClass('scrollTop')}else if($(window).scrollTop()+$(window).height()==$(document).height()){$('body').addClass('scrollBottom')}
else{$('body').removeClass('scrollTop scrollBottom')}};App.Other=function(){if(App.is_mobile){$('html').addClass('is_mobile')}};App.FullPage=function(){var page_autoScrolling=!1;var page_scrollOverflow=!1;var menu_anchors=[];var menu_titles=[];$("#menu li").each(function(index){menu_anchors.push($(this).data('menuanchor'));menu_titles.push($(this).text())});if(App.is_mobile){page_autoScrolling=!1;page_scrollOverflow=!1}
$('#afa-fullpage').fullpage({autoScrolling:page_autoScrolling,scrollOverflow:page_scrollOverflow,anchors:menu_anchors,menu:'#menu',navigationPosition:'right',navigationTooltips:menu_titles,navigation:!0,afterRender:function(){App.RemoveMainPreloader();$(".screen-reader-response").each(function(){if($(this).text().trim().length){var anchor_text=$(this).parents('.section').data('anchor');console.log(anchor_text);$("#afa-fullpage").fullpage.moveTo(anchor_text)}})}});App.doc.on('click','.arrow-link-index',function(){$("#afa-fullpage").fullpage.moveTo(2);return!1});App.doc.on('click','.arrow-link-last',function(){$("#afa-fullpage").fullpage.moveTo(1);return!1})};App.RemoveMainPreloader=function(){$('.armavir-fullpage').show();$('.preloader').fadeOut("slow")};$(document).ready(function(){App.Other();App.FullPage()})